### ISSUE TITLE
crashes with var not defined....

### ISSUE THREAD

**Issue by rtcpersonal2020** [ichier/cmus_app#2]
Traceback (most recent call last):
  File "/root/cmus_app/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/root/cmus_app/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "app.py", line 169, in fetch_full_status
    r = get_full_status()
  File "app.py", line 75, in get_full_status
    r = get_cmus_status()
  File "app.py", line 71, in get_cmus_status
    return false
NameError: global name 'false' is not defined

**Comment by ichier** [comment]
see, those things happen, when writing in foreign languages. fixed (i hope). thx!
